name: Run Tests in my project every push on GitHub

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2  
    - name: Setup Node.js
      uses: actions/setup-node@v1
      with:
        node-version: "12"
      
    - uses: actions/checkout@v2
    - name: Run Jest
      uses: stefanoeb/jest-action@1.0.3